Awesome Books Project
TekyRey/Awesome-Books pull request #1
Opened 2022-06-27 16:34 UTC by TekyRey

### **Awesome Books Project**
In this project we used plain JavaScript and html to:

- Create a html form that accepts book tittle and book author
- Store book data as objects in an array
- Add delete and add functionality
- display newly added books

2022-06-27 16:58 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @TekyRey & @henrykgggg, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Professional Readme
✔️ Good PR Title and Description
✔️ All linters passing

## Required 
- [ ] Update Readme - _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-27 16:58 UTC, sja-thedude commented on README.md
> +# Conference Page
- [ ] Kindly update the title with the current project for a clear understanding of the topic.

2022-06-27 16:58 UTC, sja-thedude commented on README.md
> +> Book Records app
- [ ] Kindly add a description of the project for a clear understanding of what the project is about.

2022-06-27 16:58 UTC, sja-thedude commented on README.md
> +👤 **Henry Karamaga**
- [ ] Kindly add the contact details of your collaborator.

2022-06-28 08:37 UTC, prolajumokeoni approved these changes
Hi @TekyRey,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 08:42 UTC, merged